---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: project-euler
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task-1: "gradle"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: build
        displayName: build gradle project
        taskRef:
          name: gradle
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        params:
          - name: GRADLE_IMAGE
            value: library/gradle:8-jdk17
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        storageClass: openebs-zfspv-satassdz2
        resources:
          requests:
            storage: 1Gi
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
